# Jason Judd Roth
# Project Euler - Problem 2
# May 15, 2013

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

sum = 0
prev = 1
prevPrev = 0
result = 0
n = 4000000

while sum < n:
	result = prev + prevPrev
	#print(result, end=' ')
	if result%2 == 0:
		sum += result
	prevPrev = prev
	prev = result
print(sum)